export enum RATINGS {
  TRY_ADD_RECIPE_RATING = 'TRY_ADD_RECIPE_RATING',
  ADDING_RECIPE_RATING = 'ADDING_RECIPE_RATING',
  ADD_RECIPE_RATING_SUCCESS = 'ADD_RECIPE_RATING_SUCCESS',
  ADD_RECIPE_RATING_FAILURE = 'ADD_RECIPE_RATING_FAILURE',

  TRY_FETCH_RECIPE_RATING = 'TRY_FETCH_RECIPE_RATING',
  FETCHING_RECIPE_RATING = 'FETCHING_RECIPE_RATING',
  FETCH_RECIPE_RATING_SUCCESS = 'FETCH_RECIPE_RATING_SUCCESS',
  FETCH_RECIPE_RATING_FAILURE = 'FETCH_RECIPE_RATING_FAILURE',

  TRY_ADD_ARTICLE_RATING = 'TRY_ADD_ARTICLE_RATING',
  ADDING_ARTICLE_RATING = 'ADDING_ARTICLE_RATING',
  ADD_ARTICLE_RATING_SUCCESS = 'ADD_ARTICLE_RATING_SUCCESS',
  ADD_ARTICLE_RATING_FAILURE = 'ADD_ARTICLE_RATING_FAILURE',

  TRY_FETCH_ARTICLE_RATING = 'TRY_FETCH_ARTICLE_RATING',
  FETCHING_ARTICLE_RATING = 'FETCH_ARTICLE_RATING',
  FETCH_ARTICLE_RATING_SUCCESS = 'FETCH_ARTICLE_RATING_SUCCESS',
  FETCH_ARTICLE_RATING_FAILURE = 'FETCH_ARTICLE_RATING_FAILURE',
}
