export enum HEADER_ACTION_TYPES {
  FETCH = 'FETCH',
  FAMILY_SELECTED = 'FAMILY_SELECTED',
  CATEGORY_SELECTED = 'CATEGORY_SELECTED',
  CATEGORY_DETAILS_FETCHED = 'CATEGORY_DETAILS_FETCHED',
  SHOW_SEARCH = 'SHOW_SEARCH',
  HIDE_SEARCH = 'HIDE_SEARCH',
  SHOW_PROFILE = 'SHOW_PROFILE',
  HIDE_PROFILE = 'HIDE_PROFILE',
}

export enum NEWSLETTER_ACTION_TYPES {
  RESET = 'RESET',
  SUBMIT = 'SUBMIT',
  SUBMITTING = 'SUBMITTING',
  ADDED_SUCCESS = 'ADDED_SUCCESS',
  ADDED_FAILURE = 'ADDED_FAILURE',
}

export enum SEARCH_ACTION_TYPES {
  SEARCH = 'SEARCH',
  SEARCHING = 'SEARCHING',
  SEARCH_SUCCESS = 'SEARCH_SUCCESS',
  SEARCH_FAILURE = 'SEARCH_FAILURE',
  CLEAR_SEARCH = 'CLEAR_SEARCH',
}
