export enum HEADER_ACTION_TYPES {
    FETCH = 'FETCH',
    FAMILY_SELECTED = 'FAMILY_SELECTED',
    CATEGORY_SELECTED = 'CATEGORY_SELECTED',
    CATEGORY_DETAILS_FETCHED = 'CATEGORY_DETAILS_FETCHED',
    TEST = 'TEST'

}