export enum PROFILE_STEPS {
  LOAD = 'LOAD',
  LOADING = 'LOADING',
  UPDATING = 'UPDATING',
  LOADING_SUCCESS = 'LOADING_SUCCESS',
  LOADING_FAILURE = 'LOADING_FAILURE',
  UPDATING_SUCCESS = 'UPDATING_SUCCESS',
  UPDATING_FAILURE = 'UPDATING_FAILURE',
  CREATE_PROFILE_DEFAULT = 'CREATE_PROFILE_DEFAULT',
  START_CREATE_PROFILE = 'START_CREATE_PROFILE',
  CREATE_PROFILE = 'CREATE_PROFILE',
  CREATING_PROFILE = 'CREATING_PROFILE',
  CREATE_PROFILE_SUCCESS = 'CREATE_PROFILE_SUCCESS',
  CREATE_PROFILE_FAILURE = 'CREATE_PROFILE_FAILURE',
}

export enum HOUSEHOLD_ROLE {
  OWNER = 'OWNER',
  APPROVING_MEMEBER = 'APPROVING_MEMBER',
  MEMEBER = 'MEMBER',
}

export interface HouseholdMember {
  firstName: string
  lastName: string
  avatar: string
  phoneNumber: string
  email: string
  password: string
  role: HOUSEHOLD_ROLE
}
