export enum PROFILE_STEPS {
  LOAD = 'LOAD',
  LOADING = 'LOADING',
  UPDATING = 'UPDATING',
  LOADING_SUCCESS = 'LOADING_SUCCESS',
  LOADING_FAILURE = 'LOADING_FAILURE',
  UPDATING_SUCCESS = 'UPDATING_SUCCESS',
  UPDATING_FAILURE = 'UPDATING_FAILURE',
}
