export enum CREATE_HOUSEHOLD_SURVEY_STEP {
  STEP1 = 'WELCOME',
  STEP2 = 'PLAN',
  STEP3 = 'HOUSEHOLD',
}

export enum CREATE_HOUSEHOLD_FROM {
  SURVEY = 'SURVEY',
  NEWSLETTER = 'NEWSLETTER,',
}

export enum CREATE_HOUSEHOLD_SURVEY_ASYNC_STEPS {
  SUBMIT = 'SUBMIT',
  SUBMITTING = 'SUBMITTING',
  SUCCESS = 'SUCCESS',
  FAILURE = 'FAILURE',
}

export enum CREATE_HOUSEHOLD_NEWLETTER_ASYNC_STEPS {
  FORM = 'FORM',
  SUBMITTING = 'SUBMITTING',
  SUCCESS = 'SUCCESS',
  FAILURE = 'FAILURE',
}
